### ISSUE TITLE
Add playtime tracking

### ISSUE THREAD

**Issue by fl0werpowers** [FriendsOfGalaxy/galaxy-integration-epic#1]
Playtime tracking has just been added to EGS, so it's about time to implement this in the integration.

**Comment by RoseTheFlower** [comment]
It even works retroactively!

**Comment by FriendsOfGalaxy** [comment]
Yup, seen that. Would be nice to add it soon.

**Comment by FriendsOfGalaxy** [comment]
Feature should be out in 0.41
