### ISSUE TITLE
The Sinking City is not detected

### ISSUE THREAD

**Issue by Silphatos** [FriendsOfGalaxy/galaxy-integration-epic#10]
All other games on my Epic account was imported fine.

**Comment by FriendsOfGalaxy** [comment]
Not detected as installed or as owned?
I need more information to check your issue. Could you please use bug report template and attach logs? https://github.com/FriendsOfGalaxy/galaxy-integration-epic/issues/new/choose

**Comment by Silphatos** [comment]
> Not detected as installed or as owned?
> I need more information to check your issue. Could you please use bug report template and attach logs? https://github.com/FriendsOfGalaxy/galaxy-integration-epic/issues/new/choose

I did some research and looks like it has been removed from the store, so I think this is not a bug after all :D 
https://www.epicgames.com/store/en-US/product/the-sinking-city
