### ISSUE TITLE
Infinite loading during sign in

### ISSUE THREAD

**Issue by sfreyux** [FriendsOfGalaxy/galaxy-integration-epic#11]
**Before start**
- check if your issue is known: https://github.com/FriendsOfGalaxy/galaxy-integration-epic/wiki/Common-problems

**Describe the bug**
After inserting my Epic Games credentials and resolving the challenge, the confirmation button turns into a spinning "loading" icon and stays like this infinitely. No error messages or anything, the only thing I can do is close the window and then on GOG settings I am "Not connected" to Epic.

**To Reproduce**
1. Log in to Epic
2. Resolve the challenge (if it asks if you're human)
3. Infinite loading

**Expected behavior**
I should log in to Epic Games and finalize the connection to GOG.

**Attached logs**
[plugin-epic-24d5f405-7211-4198-83c4-50a6f63b1dcf.log](https://github.com/FriendsOfGalaxy/galaxy-integration-epic/files/4884084/plugin-epic-24d5f405-7211-4198-83c4-50a6f63b1dcf.log)

**Comment by FriendsOfGalaxy** [comment]
Hi, this looks like issue with epic login page

**Comment by FriendsOfGalaxy** [comment]
Closing as GOG has official integration now. GOG is informed about all remaining issues.
