### ISSUE TITLE
Launch .exe directly to save time

### ISSUE THREAD

**Issue by JanPokorny** [FriendsOfGalaxy/galaxy-integration-epic#2]
Most games on Epic are able to be launched directly from .exe, not requiring the Epic client to be running. It would be nice to include a feature that switches a game to direct launch, as opposed through the Epic client.

### Pros
+ time saved (Epic happens to be exceptionally slow sometimes)
### Cons
- not compatible with DRM
  - note that not many games have it
  - also note that I have no way to check how DRM'd games on Epic behave when launched from the .exe -- if they just run the client, like Steam games do, this is a non-issue
- not compatible with cloud saves

Simplest implementation would be a manual checkbox somewhere in game settings commanding it to be launched directly. (As I believe both cloud saves and DRM status are hard, maybe impossible to detect, making this infeasible to be the default option.)

**Comment by FriendsOfGalaxy** [comment]
Thanks for proposal, I like the idea, but not as a default feature. Simultaneously look like it requires total refactor, so I won't do this in the near future.

#### This feature would also require:
- knowing which games can be run w/o launcher - how?
- providing additional option for user somehow (Galaxy do not support such feature)
- refactor process watcher (now it is optimized to watch launcher child processes)
- searching for proper executable (currently we know only directory) - registry? scanning directory heuristics?

#### Other cons:
- losing game time tracking from epic backend

**Comment by JanPokorny** [comment]
For reference, this is the same issue for Playnite: https://github.com/JosefNemec/Playnite/issues/1068

**Comment by Varstahl** [comment]
Implemented [here](https://github.com/JosefNemec/Playnite/commit/e56cafea46efd9706d6319b3ef3cc848a5742f77), installation manifest contains a flag to determine if the game can be played offline.

**Comment by FriendsOfGalaxy** [comment]
Closing as GOG has official integration now. GOG is informed about all remaining issues.
