### ISSUE TITLE
Epic integration not working anymore

### ISSUE THREAD

**Issue by darksgan** [FriendsOfGalaxy/galaxy-integration-epic#4]
The epic integration is not working anymore. It is not syncing the game list, and the Epic label remains empty

**Comment by FriendsOfGalaxy** [comment]
Hi, fix should be already deployed. Restart Galaxy and try again

**Comment by darksgan** [comment]
It seems to work now after updating. Nice job dude ;)

**Comment by Filipp0vAP** [comment]
Hello everyone!

I have the same problem on plugin version 0.48.1.
After integration, not a single game was added to GOG.
Reinstalling EGS and GOG did not help.

Any ideas how to fix it?

Thanks!

**Comment by FriendsOfGalaxy** [comment]
@Filipp0vAP does it work for you now? If not ,please share logs as described in https://github.com/FriendsOfGalaxy/galaxy-integration-epic/wiki/Log-files

**Comment by Filipp0vAP** [comment]
@FriendsOfGalaxy 
Yea! It's fixed in version 0.48.2 
THX!
