### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by micpp42** [FriendsOfGalaxy/galaxy-integration-epic#7]
I have noticed that every so often, the python process attached to the Epic Store integration will have its CPU usage shoot right up. Poking around with Process Monitor has indicated that what it seems to be doing is going through and accessing every single file in the installed Epic games. I'm not sure if this should be happening. Have attached a screenshot of process monitor.

![epic store plugin behaviour](https://user-images.githubusercontent.com/16983501/84608286-0312b680-aef5-11ea-8039-143d37c3967d.PNG)

**Comment by micpp42** [comment]
[plugin-epic-24d5f405-7211-4198-83c4-50a6f63b1dcf.log.txt](https://github.com/FriendsOfGalaxy/galaxy-integration-epic/files/4777499/plugin-epic-24d5f405-7211-4198-83c4-50a6f63b1dcf.log.txt)
Here is my log file

**Comment by FriendsOfGalaxy** [comment]
Hi, thanks for report. The problem was the same as in #6. Galaxy asks plugin frequently to get local sizes, plugin do the thing by iterating over all game files.
