### ISSUE TITLE
I don't get confirmation of my EGS password for Galaxy 2.0

### ISSUE THREAD

**Issue by DrQuakeRUS** [FriendsOfGalaxy/galaxy-integration-epic#8]
I want to enable synchronization of EGS games in Galaxy 2.0 After entering Login and Password, a window opens with the verification code. That is why it does not come to the mail, so the support replied GOG.com They advise you to contact us here.
![2020-06-17_200711](https://user-images.githubusercontent.com/29672288/85891581-001e9c80-b7f8-11ea-84bd-168d32cdc4e6.jpg)
[plugin-epic-24d5f405-7211-4198-83c4-50a6f63b1dcf.log](https://github.com/FriendsOfGalaxy/galaxy-integration-epic/files/4838803/plugin-epic-24d5f405-7211-4198-83c4-50a6f63b1dcf.log)

PS I Write through a translator.

**Comment by FriendsOfGalaxy** [comment]
Hi @DrQuakeRUS, thanks for report.

I'll try to reproduce on my own. Did you check spam folder?

**Comment by DrQuakeRUS** [comment]
Да, первым делом проверял.
Yes, I checked first.

**Comment by FriendsOfGalaxy** [comment]
I cannot reproduce, but looks like Epic has some troubles with sending emails last time:
https://www.gamerevolution.com/guides/646593-epic-games-not-sending-email-fix-how-to-get-verification-password-reset-messages

**Comment by DrQuakeRUS** [comment]
Всё возможно. Но письма с оплатой, покупкой, раздачей бесплатных игр приходят без проблем. Причём сразу.
Everything is possible. But emails with payment, purchase, and distribution of free games come without problems. And immediately.

**Comment by JanPokorny** [comment]
@DrQuakeRUS The prompt in the image states that you should get the code from an authenticator app, not by email. Did you by any chance set one up? At one point, Epic started forcing everyone to do it before claiming the next free game.

**Comment by DrQuakeRUS** [comment]
@January Pokorny I also assumed that I needed the code from the app, but I didn't find the app on either the Epic GS website or google play.

I'm closing the topic, because I managed to link my EGS account via my google account.

**Comment by JanPokorny** [comment]
@DrQuakeRUS There is no dedicated Epic app, like Steam has. Epic works with any generic OTP authenticator app, of which there are many (Google Authenticator, Microsoft Authenticator, Authy, AndOTP, Aegis...). Be sure to check this out in your Epic account settings so you don't accidentally lose your account!
